#!/usr/bin/env bash
# Customizing a 484-error_page

#Updating Packages before performing installations

sudo apt-get update sudo apt-get install -y nginx
# Creating an index.html page

echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a "moved permanently redirection" (301)

new_string="server name ;\n\trewrite ^V/redirect me https:\/\/github.com\/besthor permanent;"
new_string="server_name _;\n\trewrite ^\/redirect_ne https:\/\/github.com\/besthor permanent;"
sudo sed -1 "s/server_name _;/Snew_string/"//etc/nginx/sites-enabled/default
# Creating a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror page 404 V/484.html;\n\tlocation\/484.html {\n\t\troot /var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server:/$new_string/" /etc/nginx/sites-enabled/default
# Testing configurations for syntax errors
sudo nginx -t
# restart nginx after implementing changes
sudo service nginx restart
